import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { generateOpenApi } from '../scripts/generate-openapi.mjs';
import { getCheckoutArgument, syncOpenApi } from '../scripts/sync-openapi.mjs';

const root = resolve(process.cwd());
const snapshotPath = join(root, 'openapi/bugsport.json');
const metadataPath = join(root, 'openapi/source.json');
const sourceDigest = 'fdee88614b8222e2e92ce54f97a6292c01a0af1595aaca8ac3e3d19c4d7b6161';
const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe('OpenAPI snapshot', () => {
  it('accepts pnpm’s forwarded argument delimiter', () => {
    expect(getCheckoutArgument(['node', 'scripts/sync-openapi.mjs', '--', '/tmp/bugsport'])).toBe('/tmp/bugsport');
  });

  it('records the exact contract source and its raw-byte digest', async () => {
    const metadata = JSON.parse(await readFile(metadataPath, 'utf8'));

    expect(metadata).toMatchObject({
      repository: 'hash-line/bugsport',
      path: 'packages/contracts/openapi.json',
      commit: 'cbd9954e8a1b26cd3b507a2f7eff84c5062ec0ce',
      sha256: sourceDigest,
    });
    expect(metadata.synchronizedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it('documents project API-key authentication', async () => {
    const schema = JSON.parse(await readFile(snapshotPath, 'utf8'));

    expect(schema.components.securitySchemes.ApiKeyAuth).toMatchObject({
      type: 'apiKey',
      in: 'header',
      name: 'x-api-key',
    });
  });

  it('contains the issue ingestion route', async () => {
    const schema = JSON.parse(await readFile(snapshotPath, 'utf8'));

    expect(schema.paths['/v1/projects/{projectId}/issues'].post).toBeDefined();
  });

  it('preserves the synchronized timestamp when an identical contract is synced twice', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'bugsport-openapi-'));
    temporaryDirectories.push(directory);
    const sourcePath = join(directory, 'openapi.json');
    const outputDirectory = join(directory, 'snapshot');
    const source = JSON.stringify({
      openapi: '3.1.0',
      info: { version: '1.0.0', title: 'Fixture API' },
      paths: {
        '/v1/fixtures': {
          post: {
            responses: { '204': { description: 'No content' } },
            tags: ['fixtures', 'write'],
          },
        },
      },
    });
    await writeFile(sourcePath, source);

    await syncOpenApi(sourcePath, 'a'.repeat(40), {
      outputDirectory,
      synchronizedAt: '2026-07-26T00:00:00.000Z',
    });
    const firstMetadata = await readFile(join(outputDirectory, 'source.json'), 'utf8');

    await syncOpenApi(sourcePath, 'a'.repeat(40), {
      outputDirectory,
      synchronizedAt: '2026-07-26T00:01:00.000Z',
    });
    const secondMetadata = await readFile(join(outputDirectory, 'source.json'), 'utf8');
    const snapshot = JSON.parse(await readFile(join(outputDirectory, 'bugsport.json'), 'utf8'));

    expect(secondMetadata).toBe(firstMetadata);
    expect(snapshot.paths['/v1/fixtures'].post.tags).toEqual(['fixtures', 'write']);
    expect(JSON.parse(secondMetadata).sha256).toBe(createHash('sha256').update(source).digest('hex'));
  });

  it('generates the issue-ingestion page as a clearly marked artifact', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'bugsport-openapi-pages-'));
    temporaryDirectories.push(directory);

    await generateOpenApi(directory);
    const page = await readFile(join(directory, 'v1/projects/projectid/issues/post.mdx'), 'utf8');

    expect(page).toContain('This file was generated by Fumadocs. Do not edit this file directly.');
    expect(page).toContain('showDescription');
    expect(page).toContain('document="./openapi/bugsport.json"');
  });
});
